name: Deploy CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: packages/react-app/infra

    steps:
      - uses: actions/checkout@v2
      - name: build
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: cd ../ && yarn install
      - run: cd ../ && CI=false yarn build
      - run: npm ci
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy --domain dev.mysterydrop.app --name web --htmlSrc "../build" --hostedzoneid Z07774401NIYXMXGGQDWK
        env:
          # SERVERLESS_ACCESS_KEY: ${{secrets.SERVERLESS_ACCESS_KEY}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
