name: Deploy CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: packages/react-app

    steps:
      - uses: actions/checkout@v2
      - name: build
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - run: yarn install
      - run: CI=false yarn build
      - run: cd ./infra && npm ci
      - run: cd ./infra && npx serverless config --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: cd ./infra && npx serverless deploy --package ./infra --domain dev.mysterydrop.app --name web --htmlSrc "../build" --hostedzoneid Z07774401NIYXMXGGQDWK
