name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - env:
          - AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          - AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install
      - run: yarn build
      - run: cd packages/react-app/infra
      - run: npm ci
      - run: npx serverless deploy --domain dev.mysterydrop.app --name web --htmlSrc "../build" --hostedzoneid Z07774401NIYXMXGGQDWK
      - environment: dev
